version: "2.1"
services:
  puppetdb:
    image: eyp/puppetdb:51
    build: ./puppetdb/
    restart: always
    volumes:
      - puppetdb-data:/tmp/puppetdb
      - ./puppet-ssl:/etc/puppetlabs/puppet/ssl:rw
    networks:
      pm5net:
        aliases:
          - puppetdb
          - puppetdb.pm5.docker
    environment:
      EYP_PUPPETFQDN: 'puppet5'
      EYP_PUPPETDB_EXTERNAL_PORT: '9141'
    healthcheck:
      test: ["CMD", "/bin/true"]
      interval: 30s
      timeout: 10s
      retries: 5
  puppetboard:
    image: eyp/voxpopuli-puppetboard:51
    build: puppetpanel
    restart: always
    depends_on:
      puppetdb:
        condition: service_healthy
    volumes:
      - ./puppet-ssl:/etc/puppetlabs/puppet/ssl:rw
    networks:
      pm5net:
        aliases:
          - puppetboard
          - puppetboard.pm5.docker
    environment:
      EYP_PUPPETBOARD_PASSWORD: 'e382ff445aaf597f33f5ba43b94f5e6b'
    environment:
      PUPPETDB_HOST: puppetdb.pm5.docker
      PUPPETDB_PORT: 8081
      PUPPETDB_SSL_VERIFY: /etc/puppetlabs/puppet/ssl/puppetdb-ca.pem
      PUPPETDB_KEY: /etc/puppetlabs/puppet/ssl/private_keys/puppetdb.pm5.docker.pem
      PUPPETDB_CERT: /etc/puppetlabs/puppet/ssl/certs/puppetdb-container.pem
      INVENTORY_FACTS: 'Hostname,fqdn, IP Address,ipaddress'
      ENABLE_CATALOG: 'True'
      GRAPH_FACTS: 'architecture,puppetversion,osfamily'
    healthcheck:
      test: ["CMD", "/bin/true"]
      interval: 30s
      timeout: 10s
      retries: 5
  puppetmaster:
    image: eyp/pupppetmaster:51
    build: ./puppetmaster5
    restart: always
    depends_on:
      puppetdb:
        condition: service_healthy
    environment:
      EYP_PUPPETFQDN: 'puppet5'
      EYP_PM_SSL_REPO: ''
      EYP_PM_CUSTOMER_REPO: ''
    networks:
      pm5net:
        aliases:
          - puppet5
          - puppet5.pm5.docker
    volumes:
      - ./ssh:/root/.ssh:ro
      - ./utils:/opt/utils:ro
    healthcheck:
      test: ["CMD", "curl", "--insecure", "https://localhost:8140"]
      interval: 60s
      timeout: 10s
      retries: 10

volumes:
  puppetdb-data:

networks:
  pm5net:
    driver: bridge
